# src/server/core/use_cases/fundamental.py
"""Fundamental data use cases shared by MCP tools and REST routes.

Design note
-----------
Simple gateway-delegation use cases are generated by ``_gw_usecase``.
Only functions that add business logic (orchestration, multi-step calls,
service-layer delegation) are written by hand.

Adding a new gateway-delegating use case:
    1. Make sure the method exists in _TICKER_METHODS / _MARKET_METHODS
       inside market_gateway.py.
    2. Add one line here:
           get_my_new_data = _gw_usecase("get_my_new_data")
    Done.
"""

from __future__ import annotations

from typing import Any, Callable, Dict

from src.server.core.dependencies import Container
from src.server.utils.logger import logger


# ---------------------------------------------------------------------------
# Factory: generates a coroutine function that logs + delegates to gateway
# ---------------------------------------------------------------------------


def _gw_usecase(method: str) -> Callable:
    """Return an async function that calls gateway.<method>(symbol, **kwargs).

    The generated function's signature is:
        async (symbol: str, **kwargs) -> Dict[str, Any]
    """

    async def _fn(symbol: str, **kwargs) -> Dict[str, Any]:
        gateway = Container.market_gateway()
        logger.info(f"UseCase: {method}", symbol=symbol, **kwargs)
        return await getattr(gateway, method)(symbol, **kwargs)

    _fn.__name__ = method
    _fn.__qualname__ = f"use_cases.fundamental.{method}"
    return _fn


# ---------------------------------------------------------------------------
# Gateway-delegating use cases (one line each)
# ---------------------------------------------------------------------------

get_financials = _gw_usecase("get_financials")
get_mainbz_info = _gw_usecase("get_mainbz_info")
get_shareholder_info = _gw_usecase("get_shareholder_info")
get_dividend_info = _gw_usecase("get_dividend_info")
get_valuation_metrics = _gw_usecase("get_valuation_metrics")
# US fundamental
get_earnings_history = _gw_usecase("get_earnings_history")
get_cash_flow_quality = _gw_usecase("get_cash_flow_quality")
get_us_valuation_metrics = _gw_usecase("get_us_valuation_metrics")
get_us_institutional_holdings = _gw_usecase("get_us_institutional_holdings")


# ---------------------------------------------------------------------------
# Non-trivial use cases (hand-written — these do real orchestration)
# ---------------------------------------------------------------------------


async def get_fundamental_analysis(ticker: str) -> Dict[str, Any]:
    """Full fundamental analysis: resolves symbol first, then calls service."""
    service = Container.fundamental_service()
    gateway = Container.market_gateway()
    resolved = await gateway.resolve_ticker(ticker)
    logger.info(
        "UseCase: get_fundamental_analysis",
        symbol=ticker,
        resolved_ticker=resolved,
    )
    return await service.get_fundamental_analysis(resolved)
