# src/server/core/use_cases/technical.py
"""Technical analysis use cases shared by MCP tools and REST routes.

Design note
-----------
- Service-layer use cases (CN technical analysis) are hand-written because
  they call Container.technical_service() with positional kwargs.
- Gateway-delegating use cases (US market) are generated by ``_gw_usecase``
  imported from fundamental — same factory, zero duplication.

Adding a new US gateway use case:
    1. Ensure the method is in _TICKER_METHODS or _MARKET_METHODS in gateway.
    2. Add one line: get_my_method = _gw_usecase("get_my_method")
"""

from __future__ import annotations

from typing import Any, Dict

from src.server.core.dependencies import Container
from src.server.utils.logger import logger
from src.server.core.use_cases.fundamental import _gw_usecase


# ---------------------------------------------------------------------------
# Service-layer use cases (CN technical — hand-written, non-trivial)
# ---------------------------------------------------------------------------


async def calculate_technical_indicators(
    symbol: str, period: str = "30d", interval: str = "1d", limit: int | None = None
) -> Dict[str, Any]:
    service = Container.technical_service()
    logger.info(
        "UseCase: calculate_technical_indicators",
        symbol=symbol,
        period=period,
        interval=interval,
        limit=limit,
    )
    result = await service.calculate_indicators(
        symbol=symbol, period=period, interval=interval, limit=limit
    )
    return result


async def analyze_price_patterns(symbol: str, period: str = "90d") -> Dict[str, Any]:
    service = Container.technical_service()
    logger.info("UseCase: analyze_price_patterns", symbol=symbol, period=period)
    return await service.analyze_price_patterns(symbol=symbol, period=period)


async def calculate_support_resistance(
    symbol: str, period: str = "90d"
) -> Dict[str, Any]:
    service = Container.technical_service()
    logger.info("UseCase: calculate_support_resistance", symbol=symbol, period=period)
    return await service.calculate_support_resistance(symbol=symbol, period=period)


async def analyze_volume_profile(symbol: str, period: str = "90d") -> Dict[str, Any]:
    service = Container.technical_service()
    logger.info("UseCase: analyze_volume_profile", symbol=symbol, period=period)
    return await service.analyze_volume_profile(symbol=symbol, period=period)


async def generate_trading_signal(
    symbol: str, period: str = "90d", interval: str = "1d"
) -> Dict[str, Any]:
    service = Container.technical_service()
    logger.info(
        "UseCase: generate_trading_signal",
        symbol=symbol,
        period=period,
        interval=interval,
    )
    return await service.generate_trading_signal(
        symbol=symbol, period=period, interval=interval
    )


# ---------------------------------------------------------------------------
# US gateway-delegating use cases (one line each via _gw_usecase factory)
# ---------------------------------------------------------------------------

get_us_price_history = _gw_usecase("get_us_price_history")
get_us_volume_analysis = _gw_usecase("get_us_volume_analysis")
get_us_sector_etf_analysis = _gw_usecase("get_us_sector_etf_analysis")
